# MIT License
# ... (라이선스 헤더는 동일) ...

bridge:
  ros__parameters:
    ego_namespace: 'ego_racecar'
    ego_scan_topic: '/ego_racecar/scan'
    ego_odom_topic: 'odom'           # (브리지가 네임스페이스 내부에서 발행)
    ego_opp_odom_topic: 'opp_odom'   # 필요시 유지
    ego_drive_topic: '/ego_racecar/drive'

    opp_namespace: 'opp_racecar'
    opp_scan_topic: '/opp_racecar/opp_scan'
    opp_odom_topic: 'odom'
    opp_ego_odom_topic: 'opp_odom'
    opp_drive_topic: '/opp_racecar/opp_drive'

    num_agent: 2 
    kb_teleop: False       # PP가 /ego_racecar/drive로 직접 운전하게
    publish_tf: True

    # ===================================================

    # transform related
    scan_distance_to_base_link: 0.0 # (나중에 0.275 등으로 수정하는 것을 추천)

    # laserscan parameters
    scan_fov: 4.7
    scan_beams: 1080

    # map parameters (사용자 설정 유지)
    map_path: '/sim_ws/src/f1tenth_gym_ros/maps/E1_out2_obs24'
    map_img_ext: '.pgm'

    # ego starting pose on map (사용자 설정 유지)
    sx: 0.0
    sy: 0.0
    stheta: 0.0

    # opp starting pose on map (사용자 설정 유지)
    sx1: 2.0
    sy1: 0.5
    stheta1: 0.0

